var LETS_MEET_API = 'http://letsmeet.intel.com:8055/REST';
var LETS_MEET_API_KEY = '24D661C7-0605-4462-8A25-29B2C34653B9';

var BOT_USER_ID = 'U0GPNKZ3P';
var BOT_CHANNEL_ID = 'C0GPN3KV2';
var BOT_CHANNEL_NAME = '#bot_channel';

var PERSISTENCY_FILENAME = 'persistence.txt';

var DEFAULT_BUILDING = 'IDC11';

var PERSISTENCY_OBJECTS = {
    USERS : 'users',
    REMINDERS : 'reminders'
};

module.exports = {
    LETS_MEET_API : LETS_MEET_API,
    LETS_MEET_API_KEY : LETS_MEET_API_KEY,
    BOT_USER_ID : BOT_USER_ID,
    BOT_CHANNEL_ID : BOT_CHANNEL_ID,
    BOT_CHANNEL_NAME : BOT_CHANNEL_NAME,
    PERSISTENCY_FILENAME : PERSISTENCY_FILENAME,
    DEFAULT_BUILDING : DEFAULT_BUILDING,
    PERSISTENCY_OBJECTS : PERSISTENCY_OBJECTS
};
